export const VSCODE_COLORS = {
  bg: '#1e1e1e',
  sidebar: '#252526',
  activityBar: '#333333',
  statusBar: '#007acc',
  titleBar: '#3c3c3c',
  border: '#2b2b2b',
  text: '#cccccc',
  textActive: '#ffffff',
  accent: '#007acc',
  tabActive: '#1e1e1e',
  tabInactive: '#2d2d2d',
}

export const LANGUAGE_MAP: Record<string, string> = {
  ts: 'typescript',
  tsx: 'typescript',
  js: 'javascript',
  jsx: 'javascript',
  css: 'css',
  html: 'html',
  json: 'json',
  md: 'markdown',
  txt: 'plaintext',
  py: 'python',
  java: 'java',
  go: 'go',
  rs: 'rust',
  c: 'c',
  cpp: 'cpp',
  cs: 'csharp',
  php: 'php',
  xml: 'xml',
  yml: 'yaml',
  yaml: 'yaml',
  sql: 'sql',
}
